### ISSUE TITLE
Implement a REST interface

### ISSUE THREAD

**Issue by trzcioli** [adrianmisko/scenario-quality-checker#2]
# Implement a RESTful API
- [x] setting up endpoints
- [x] getting JSON input
- [x] processing & storing data in memory (specific features later)
- [x] checking if scenario with such title already exists
- [x] returning JSON output
- [x] error handling
- [x] logging

**Comment by adrianmisko** [comment]
- POST: /scenarios/add - adds scenario and returns it's ID 
- GET /scenarios/{id}, requestParam: ?get='API feature'

**Comment by adrianmisko** [comment]
Should scenarios be unique based on title?
